CRITICAL - 2022-03-29 11:05:54 --> Invalid file: part/header.php
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('part/header.php')
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('part/header', Array, true)
#2 C:\xampp\htdocs\myTest_Project\app\Controllers\Home.php(9): view('part/header')
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->index()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-03-29 11:08:18 --> Call to a member function view() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->index()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-03-29 11:08:19 --> Call to a member function view() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->index()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-03-29 11:57:27 --> Call to a member function post() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-03-29 11:57:32 --> Call to a member function post() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-03-29 11:57:40 --> Call to a member function post() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-03-29 11:58:34 --> Call to a member function post() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-03-29 11:58:36 --> Call to a member function post() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-03-29 11:59:23 --> Call to a member function post() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-03-29 12:00:03 --> Call to a member function post() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-03-29 12:01:24 --> Call to a member function post() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-03-29 12:03:14 --> Call to a member function post() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-03-29 12:05:10 --> Call to a member function post() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-03-29 12:07:48 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(20): redirect('login')
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-03-29 12:08:00 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(20): redirect('login')
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-03-29 12:32:54 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Model.php(545): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Model.php(693): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(21): CodeIgniter\Model->__get('cek_login')
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-03-29 12:33:52 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Model.php(545): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Model.php(693): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(21): CodeIgniter\Model->__get('cek_login')
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
ERROR - 2022-03-29 12:34:44 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-03-29 12:34:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\myTest_Project\app\Models\M_login.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#2 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(21): App\Models\M_login->cek_login('sw')
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
ERROR - 2022-03-29 12:35:14 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-03-29 12:35:14 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\myTest_Project\app\Models\M_login.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#2 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(21): App\Models\M_login->cek_login('furizal123')
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
ERROR - 2022-03-29 12:36:03 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-03-29 12:36:03 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\myTest_Project\app\Models\M_login.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#2 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(21): App\Models\M_login->cek_login('furizal123')
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
ERROR - 2022-03-29 12:36:05 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-03-29 12:36:05 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\myTest_Project\app\Models\M_login.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#2 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(21): App\Models\M_login->cek_login('furizal123')
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
ERROR - 2022-03-29 12:36:06 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-03-29 12:36:06 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\myTest_Project\app\Models\M_login.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#2 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(21): App\Models\M_login->cek_login('furizal123')
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
ERROR - 2022-03-29 12:36:35 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-03-29 12:36:35 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\myTest_Project\app\Models\M_login.php(10): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#2 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(21): App\Models\M_login->cek_login('sd')
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-03-29 12:41:11 --> Call to a member function cek_login() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-03-29 12:41:57 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(48): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-03-29 12:42:49 --> Call to a member function set_flashdata() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-03-29 12:45:13 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(48): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-03-29 12:53:52 --> Call to a member function flashdata() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\View\View.php(210): include()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('v_login', Array, true)
#3 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(12): view('v_login')
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->index()
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#6 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-03-29 12:54:08 --> Call to a member function flashdata() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\View\View.php(210): include()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('v_login', Array, true)
#3 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(12): view('v_login')
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->index()
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#6 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-03-29 12:54:09 --> Call to a member function flashdata() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\View\View.php(210): include()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('v_login', Array, true)
#3 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(12): view('v_login')
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->index()
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#6 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-03-29 12:55:34 --> Call to a member function getFlashdata() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\View\View.php(210): include()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('v_login', Array, true)
#3 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(12): view('v_login')
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->index()
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#6 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-03-29 12:55:35 --> Call to a member function getFlashdata() on null
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\View\View.php(210): include()
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('v_login', Array, true)
#3 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(12): view('v_login')
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->index()
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#6 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-03-29 12:57:46 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(51): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-03-29 12:58:36 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(51): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-03-29 13:01:39 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(52): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-03-29 13:03:32 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(52): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-03-29 13:04:27 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(52): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-03-29 13:06:53 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(52): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-03-29 13:07:53 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\myTest_Project\app\Controllers\Login.php(52): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Login->proses_login()
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-03-29 13:17:31 --> session_destroy(): Trying to destroy uninitialized session
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'session_destroy...', 'C:\\xampp\\htdocs...', 12, Array)
#1 C:\xampp\htdocs\myTest_Project\app\Controllers\Logout.php(12): session_destroy()
#2 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Logout->index()
#3 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logout))
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-03-29 18:14:00 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\myTest_Project\app\Controllers\Home.php(14): redirect('http://localhos...')
#3 C:\xampp\htdocs\myTest_Project\app\Controllers\Home.php(27): App\Controllers\Home->constract()
#4 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->index()
#5 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\myTest_Project\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\myTest_Project\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-03-29 18:19:10 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:19:18 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:19:30 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:20:29 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:20:29 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:20:30 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:20:30 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:20:30 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:20:30 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:20:30 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:21:11 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:21:28 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:21:28 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:21:36 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:21:37 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:21:37 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:31:58 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:32:55 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:32:58 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:33:09 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:33:12 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:33:14 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:33:18 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:33:21 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:33:25 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:35:15 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:35:17 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:35:22 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-29 18:35:27 --> Cannot declare class App\Controllers\Home, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
